### ISSUE TITLE
There is no `models.SEOSetting` struct despite the reference is `db/seeds/main.go`

### ISSUE THREAD

**Issue by sunwukonga** [qor/qor-example#51]
Getting `db/seeds/main.go:166: undefined: models.SEOSetting` when running:

`go run db/seeds/main.go db/seeds/seeds.go`

I've temporarily removed the offending code for myself, but I suppose it would be better to add the SEOSetting struct to models.

**Comment by Noah-Heil** [comment]
Ok so I have been working a little with the QOR framework and first off I have to say that you guys are some sort of awesome for all the super slick features you have managed to pack in...however I have run into a very similar issue that the above user had as you can see here:

![selection_002](https://cloud.githubusercontent.com/assets/17733701/21686618/4e23a0dc-d323-11e6-934d-c0830726c8b4.png)

However I happened to have been perusing the newest changes you guys made (oh and PS by the way....great job on the recent releases they bring some really nice extra utility to the app) but I had noticed what the solution for the first 4 errors and well in the end I figured out the problem and solved it and have since submitted a pull request with the changes I made (including a change to the docs here and there so that others wont have to suffer as much as I had to  while getting set up)!

(screen shot referencing the solution for the first four issues:
![selection_004](https://cloud.githubusercontent.com/assets/17733701/21689398/6aaff0a2-d32d-11e6-910c-835c15d8d3d6.png)
)

In reference to the missing model I have not done anything in reference to that issue due to the fact I am pretty sure you guys are just finishing up renovating the code-base. 

Thanks for reading!

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
