### ISSUE TITLE
faceted search / searchkit integration

### ISSUE THREAD

**Issue by roscopecoltran** [qor/qor-example#56]
Hi guys,

Hope you are all well !

I am working now 2 weeks on **qor** and start to get the core principles of your framework :-) As I said earlier the setup process could be made more easier by pointing developers to a core stable release. But, I still think that in a couple of months it will be a robust e-commerce framework. 

I was wondering these 2 quick and simple questions below about qor framework, hoping you, the qor team, will have some spare time to share your insights about them:

**1. How to integrate a new pages or widgets with custom packages ?**
For example, i'd like to add a search page with the [searchkit](https://github.com/searchkit/searchkit) package and get it nicely integrated to qor-example ? What would be the best pratices (knowing that i will use a docker compose for elasticsearch and another micro-service for importing data from the gorm model, and create a new endpoint for getting search results) ? 

**More simply, how/where to copy/paste the [code](https://github.com/searchkit/searchkit#quick-intro) for a frontend/backend integration in qor ?**

**2. vue.js bindings / gopherjs**
How would it be possible to extend the admin ui with other boilerplates like the one mentioned below and get more advanced widgets for analytics or content browsing ?
- https://github.com/vue-bulma/vue-admin 
- https://github.com/marmelab/admin-on-rest
- https://github.com/rorikurniadi/vuejs-AdminLTE

**More simply :-) how it is the more convenient to build an extendable admin rest api, exporting the orm schema, like [ezorm](https://github.com/ezbuy/ezorm), and to wrap more complex setup in qor** 

Thanks in advance for your reply and responses, meanwhile, have an awesome day ! :-)

Cheers,
Richard

**Comment by jinzhu** [comment]
Hi @roscopecoltran 

Sorry for the delay and thank you for your comments.

Do you want to integrate `seaerchkit` into qor admin's search? you are possible to customize the `SearchHandler` for each registered Resource, by default, QOR will use SQL search with configured `SearchAttr`

For the second question, QOR does provide RESTful API by default, so I guess you could use those admin with QOR's restful API, although I haven't try ;)

Due to RESTFul API is not expressive enough for some complicated features, so we can't use it as a default solution ;(
